### ISSUE TITLE
@JsonInclude(NON_DEFAULT) doesn't omit null fields

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#1351]
Jackson 2.8.0

1. I set `ObjectMapper.setSerializationInclusion(NON_DEFAULT)`.
2. I have a POJO without a default constructor containing a `double` field and a `LocalDate` field. The fields are set to `0` and `null` respectively.
3. When I serialize the POJO, the `null` date gets serialized but the `double` gets omitted.

I am expecting both fields to get omitted because both contain the type's default value.

**Comment by cowwoc** [comment]
I can reproduce the same problem if I replace the date with a `String` and even if I set `@JsonInclude(NON_DEFAULT)` on the null field (it still gets serialized).

**Comment by cowtowncoder** [comment]
I'd need more complete explanation to make sure I understand. But as to `NON_DEFAULT`, it has two distinct modes:

1. When used for specific class, it will try to use default values for properties as assigned by the default no-arguments constructor: one must exist.
2. If used on property or as global default inclusion, value to check are default values for the type (in case of scalars, value that a class member would be initialized to; for other types, same as "empty" value)

So with global defaults, excluded value for double should be just `0.0`. For `LocalDate` I would except `null` or one with timestamp of `0`; although that depends on `LocalDate` serializer defining that rule (via `isEmpty()`).

Put another way, rules for `LocalDate` and `String` should be identical to `NON_EMPTY` unless annotation was used on POJO class that defines properties.

**Comment by cowwoc** [comment]
Here is a minimal testcase for your review:

```
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;

public class Main {

    public final String first;
    public final double second;

    public Main(String first, double second) {
        this.first = first;
        this.second = second;
    }

    public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper om = new ObjectMapper().setSerializationInclusion(Include.NON_DEFAULT);
        ObjectWriter writer = om.writerWithDefaultPrettyPrinter();
        String result = writer.writeValueAsString(new Main(null, 0));
        System.out.println("result: " + result);
    }
}
```

This outputs:

```
result: {
  "first" : null
}
```

I am expecting it to output:

```
result: {}
```

Does this help?

**Comment by cowtowncoder** [comment]
@cowwoc Thanks, it does: result seems wrong to me indeed. 

For sake of completeness, I just released 2.8.2 yesterday, so maybe worth checking out. Otherwise I'll look into this when I get a chance. Thank you for reporting the issue.

**Comment by cowwoc** [comment]
Just checked, 2.8.2 has the same behavior. Thanks for confirming this is a bug.

**Comment by cowtowncoder** [comment]
Hmmh. I can see where this occurs but looks like solution may get trickier than I thought.
There is the case of using `NON_DEFAULT` on a class, and in that case `null` or empty String are only to be suppressed if that's the default value for property. This should not apply here, since setting is the global default,  but somehow does. Trying to figure out what gives.

**Comment by cowtowncoder** [comment]
Needed bit bigger changes than I hoped for, but this is now fixed for 2.8.3 and should reliably detect cases where `null` should be suppressed.

**Comment by arifogel** [comment]
This is not fixed for me. I have created a pull request https://github.com/FasterXML/jackson-databind/pull/1416 with a modified version of the test @cowtowncoder added that still fails.
