### ISSUE TITLE
Jackson does not support deserializing java.util.Collections.UnmodifiableList

### ISSUE THREAD

**Issue by jpbassinello** [FasterXML/jackson-databind#3404]
**Describe the bug**
JDK 16 introduced `Stream#toList()` which creates `UnmodifiableList` while `.collect(Collectors.toList())` generates `ArrayList`.
Changing the old collectors toList with the direct call to  `Stream#toList()` caused errors when working with `defaultTyping`.

**Version information**
jackson 2.13.1
jdk 16

**To Reproduce**

```
public static void main(String[] args) throws JsonProcessingException {
    var objectMapper = new ObjectMapper()
        .activateDefaultTyping(LaissezFaireSubTypeValidator.instance, ObjectMapper.DefaultTyping.NON_FINAL);

    // works
    var list1 = Stream.of("a", "b", "c").collect(Collectors.toList());
    var json1 = objectMapper.writeValueAsString(list1);
    var deserealized1 = objectMapper.readValue(json1, Object.class);
    System.out.println(deserealized1);

    // fails
    var list2 = Stream.of("a", "b", "c").toList();
    var json2 = objectMapper.writeValueAsString(list2);
    var deserealized2 = objectMapper.readValue(json2, Object.class);
    System.out.println(deserealized2);
  }
```

**Expected behavior**
It is expected Jackson to deserialize the types correctly.

**Additional context**
Probably related issue: https://github.com/FasterXML/jackson-databind/issues/2900

**Comment by cowtowncoder** [comment]
Ok, there is also #3344 which is fixed but not yet released (will be in 2.13.2, to be released quite soon).

I'll see if I can verify this now; thank you for reporting it!

**Comment by cowtowncoder** [comment]
Ok. So, looks like this would be working now; probably due to somewhat general fix for #3344.
I'll see if I can figure out a way to add the test -- problem being Jackson not using JDK 16 for building by default.
But there are profiles set up for some other tests so it should be ok.

**Comment by pilak** [comment]
sorry to repoen this thread but the given test case still fail using JDK 19 + databind 2.15.2

> **Describe the bug** JDK 16 introduced `Stream#toList()` which creates `UnmodifiableList` while `.collect(Collectors.toList())` generates `ArrayList`. Changing the old collectors toList with the direct call to `Stream#toList()` caused errors when deserealizing with `defaultTyping` configuration
> 
> Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'a' as a subtype of `java.lang.Object`: no such class found
> 
> **Version information** jackson 2.13.1 jdk 16
> 
> **To Reproduce**
> 
> ```
> public static void main(String[] args) throws JsonProcessingException {
>     var objectMapper = new ObjectMapper()
>         .activateDefaultTyping(LaissezFaireSubTypeValidator.instance, ObjectMapper.DefaultTyping.NON_FINAL);
> 
>     // works
>     var list1 = Stream.of("a", "b", "c").collect(Collectors.toList());
>     var json1 = objectMapper.writeValueAsString(list1);
>     var deserealized1 = objectMapper.readValue(json1, Object.class);
>     System.out.println(deserealized1);
> 
>     // fails
>     var list2 = Stream.of("a", "b", "c").toList();
>     var json2 = objectMapper.writeValueAsString(list2);
>     var deserealized2 = objectMapper.readValue(json2, Object.class);
>     System.out.println(deserealized2);
>   }
> ```
> 
> **Expected behavior** It is expected Jackson to deserialize the types correctly.
> 
> **Additional context** Probably related issue: #2900

**Comment by pjfanning** [comment]
@pilak please open a new issue. There is little point commenting on an issue that was closed 18 months ago - even you think that the fix for this was incomplete.

**Comment by pjfanning** [comment]
@pilak There is a test case called Java17CollectionsTest that includes a test for `.toList` and it appears to work. This test does not use `activateDefaultTyping` though. Can you provide LaissezFaireSubTypeValidator code? - because otherwise we will need to guess what your set up is.

**Comment by pilak** [comment]
hello @pjfanning the validator is jackson domain :point_right: com.fasterxml.jackson.databind.jsontype.impl.LaissezFaireSubTypeValidator

**Comment by cowtowncoder** [comment]
Yeah this is different issue because Polymorphic Deserialization is used for some reason. Definitely need a new issue -- we usually do not re-open issues marked as fixed in release notes (but only during development when no release contains fix).

**Comment by pilak** [comment]
Are you suggesting me to create a new issue according to this use case?
