### ISSUE TITLE
Stream not closed if IOException thrown while creating parser

### ISSUE THREAD

**Issue by josh-byster** [FasterXML/jackson-databind#3455]
v2.12.4

Hi, I've noticed that, ` ObjectMapper#readValue(URL src, Class<T> valueType)`, for example, will not close the stream if reading from the URL causes, say, a `FileNotFoundException`. The exception is thrown in the [createParser](https://github.com/FasterXML/jackson-databind/blob/3bae019c8c91def310ed9679806217cff52e8c52/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L3583) invocation, and so it is not caught by the `_readMapAndClose` call. I'm able to verify this by creating many instances to a URL that returns a 200—in these cases, `netstat` shows only one connection to the server. In the case of a URL returning a 404, there are many requests sitting in `ESTABLISHED`, and then proceed to hang in `CLOSE_WAIT`.

```
java.io.FileNotFoundException:
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at com.fasterxml.jackson.core.TokenStreamFactory._optimizedStreamFromURL(TokenStreamFactory.java:211)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1057)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3479)
	at Main.main(Main.java:18)
```

**Comment by cowtowncoder** [comment]
I am not sure I follow: if the exception is thrown (as shown by stack trace) by:

```
        return url.openStream();
```

there is no `InputStream` returned to Jackson, and nothing for it to close. So I am not sure what else could be done.

**Comment by fxha** [comment]
@cowtowncoder @josh-byster We got a similar issue and I guess #3508 is related to this. Please read the linked issue first because I don't want to repeat myself.

**Describe the bug:**

The leak most likely occurs in `JsonFactory#createParser(File f)` and `JsonFactory#createParser(URL url)` because an exception is thrown during creation of the parser. A simply try-with-resources would be great to ensure that the stream is closed but I don't know whether side effects are possible when closing a stream twice.

Stack Trace:

```
readBytes:-1, FileInputStream (java.io)
read:279, FileInputStream (java.io)
ensureLoaded:539, ByteSourceJsonBootstrapper (com.fasterxml.jackson.core.json)
detectEncoding:133, ByteSourceJsonBootstrapper (com.fasterxml.jackson.core.json)
constructParser:256, ByteSourceJsonBootstrapper (com.fasterxml.jackson.core.json)
_createParser:1655, JsonFactory (com.fasterxml.jackson.core)
createParser:1030, JsonFactory (com.fasterxml.jackson.core)
readValue:3494, ObjectMapper (com.fasterxml.jackson.databind)
testJacksonBug:32, MainTest
```

**Version information:**
v2.13.3

**To Reproduce:**

Note same as in #3508: You need to successfully create a stream but where you don't have access to the files' content. Prevent access to the file will throw an exception during stream creation and no file descriptor is created. You still need  to use Windows because locking a file on Unix behaves differently.

1. Create a demo Java project with both jackson core and databind on _Windows_!
2.  Create a JUnit 5 test
3.  Copy example code

```java
class MainTest {
    @TempDir
    File tempDir;

    @Test
    void testJacksonBug() throws IOException {
        Path filePath = Paths.get(tempDir.getAbsolutePath(), "example.json");
        try (FileOutputStream outputStream = new FileOutputStream(filePath.toString());
             FileChannel channel = outputStream.getChannel();
             FileLock lock = channel.lock()) {
            channel.write(ByteBuffer.wrap("{\"value\":1}".getBytes(StandardCharsets.UTF_8)));

            assertThrows(IOException.class, () -> new ObjectMapper().readValue(filePath.toFile(), JsonEntry.class));
        }

        assertTrue(filePath.toFile().delete());
    }

    private static class JsonEntry {
        public int value = 1;
    }
}
```

Edit: maybe you need to force flush the buffer of the channel.

**Comment by cowtowncoder** [comment]
@fxha No, please file a separate new issue instead of adding to an existing one -- unless it's simply confirming existing problem. But note that anything that requires use of Windows (or MacOS or some other specific platform) will not be very helpful; I do not have a windows machine myself, but as importantly it is not possible (or practical) to automate such tests for CI.

But, still -- if the exception is thrown when constructing an `InputStream`, there is quite literally nothing Jackson can do is there? That would sound more like an OS (or JDK) bug.

**Comment by fxha** [comment]
> It might make sense to remove the description and just add a mention of #3508 as possibly related.

I do not understand what you mean by this. Do you want to merge the issues?

> I'd still like to know what is happening on reader side since I do not yet see a plausible scenario.

The managed stream by Jackson is only closed after successfully initialization when `_readMapAndClose` is executed. In the error case, the exception occurs during initialization and the stream is leaked:

1. [`JsonFactory#createParser(File f)`](https://github.com/FasterXML/jackson-core/blob/0190c3a0db81867eab6c29f8d18f7ba3ec7cf11d/src/main/java/com/fasterxml/jackson/core/JsonFactory.java#L1029) creates an input stream from the given file.
2. [`ByteSourceJsonBootstrapper#constructParser`](https://github.com/FasterXML/jackson-core/blob/0190c3a0db81867eab6c29f8d18f7ba3ec7cf11d/src/main/java/com/fasterxml/jackson/core/json/ByteSourceJsonBootstrapper.java#L256) in `jackson.core` raise an IOException due to a failure in `detectEncoding` (see stack trace above).
3. The parser, e.g. `UTF8StreamJsonParser` which should own the input stream, is never created and we never execute `_readMapAndClose`.
4. The input stream from `JsonFactory#createParser(File f)` is leaked because neither the initial method nor `UTF8StreamJsonParser` closes the stream.

The same will most likely apply to `URL` as well.

A simple solution would be to create the stream with try-with-resources and call `readValue(InputStream src, ...)`. Otherwise, catching the exception from `_createParser` in `JsonFactory#createParser` and closing the stream in an error case would work too. I'm a little bit lost about the ownership of the input stream in the latter case because `ByteSourceJsonBootstrapper` doesn't own the stream at this moment.

**Comment by josh-byster** [comment]
> there is no InputStream returned to Jackson, and nothing for it to close.


@fxha explains it exactly right; Jackson instantiates the stream internally (not passed from the client) and thus is responsible for closing it if an exception occurs. There is no way for the client to manually close the internally created stream on an exception, hence there's a resource leak.

**Comment by cowtowncoder** [comment]
@josh-byster I am not questioning that part at all, just to be sure. I was trying to figure out how to actually reproduce that this is happening. 

@fxha on my comment: sorry, no, did not mean merging. But I think misread your comment -- it DOES actually cover this issue, not the other one. Somehow I first read it as describing output side issue. My apologies.

**Comment by cowtowncoder** [comment]
@fxha Thank you very much for further elaboration of the sequence of events here.

Of possible solutions, I agree, ownership gets bit hazy at this point, but I think it should be responsibility of `JsonFactory` in:

```
    protected JsonParser _createParser(InputStream in, IOContext ctxt) throws IOException {
        // As per [JACKSON-259], may want to fully disable canonicalization:
        return new ByteSourceJsonBootstrapper(ctxt, in).constructParser(_parserFeatures,
                _objectCodec, _byteSymbolCanonicalizer, _rootCharSymbols, _factoryFeatures);
    }
```

to first of all catch (and rethrow) possible exceptions and in such case close `InputStream` if (and only if!)

```
ctxt.isResourceManaged()
```

returns `true` (to indicate input source is managed).

The alternative of `ObjectMapper` using try-with-resources would probably not work for all cases.
Alternatively we could add handling in bootstrapper, similar to factory.

This same issue will also affect other format backend implementations so it'd be good to figure out a reproduction and try those too, and fix the problem as I suspect most if not all suffer from the same problem.

**Comment by cowtowncoder** [comment]
Ok, I think I know a relatively easy way to inject a custom `InputStream` that can throw necessary exception: sub-class `JsonFactory`, override `_optimizedStreamFromURL` -- if so, construction from `URL` can be tested.
To do the same for `File` sourced thing, a bit of refactoring of `JsonFactory` (for 2.14) can be done to create overridable method.
This would allow repro against JSON factory but something similar needed for other formats.

Still, this seems quite doable. Hoping to find time this week to do that, unless someone beats me to it.

**Comment by cowtowncoder** [comment]
Quick note:

1. I think fix should go in 2.14 -- I think there's a slightly higher than usual chance of regression, and 2.14.0 may well go out before 2.13.4
2. I added helper methods `_createInputStream(File)` and `_createOutputStream(File)` for `JsonFactory` (impls) to use (in 2.14 branch) overriding of which would make it easier to inject exception-throwing input/output streams

**Comment by cowtowncoder** [comment]
Ok, I think this is fixed in `2.14` branch via 

https://github.com/FasterXML/jackson-core/issues/763

so if anyone could test with 2.14.0-SNAPSHOT (local build or via Sonatype OSS snapshots) that'd be great.
(there are basic unit tests for `JsonFactory` but would need to verify handling via `ObjectMapper`)

**Comment by cowtowncoder** [comment]
The only concern (besides sanity checking) here is that the original report suggests problem with URL in different place -- but I don't see how that would happen, as opposed to the problem fixed (which makes sense).

I will close this assuming issue is fixed, but please re-open if another reproduction found.

**Comment by josh-byster** [comment]
Thank you for looking into this @cowtowncoder! Unfortunately I believe your concern is correct that the stack trace shows a problem in a different place—I still get lots of `CLOSE_WAIT`s when running on `2.14.0-SNAPSHOT`. I set a breakpoint where your changes were made, and I don't see those getting hit. I think the problem is that the exception is actually being thrown upon opening the stream in `_optimizedStreamFromURL`.
A simple way to reproduce:
```
public class Main {
    public static void main(String[] args) throws InterruptedException {
        ObjectMapper myMapper = new ObjectMapper();
        for (int i = 0; i < 100; i++) {
            try {
                myMapper.readValue(new URL("http://localhost:3001/"), String.class);
            } catch (IOException aE) {
                aE.printStackTrace();
            }
        }
        Thread.sleep(Integer.MAX_VALUE);
    }
}
```

Running with a simple ExpressJS server that just throws a 404:

```
const express = require('express')
const app = express()
const port = 3001

app.get('/', (req, res) => {
  res.status(404).send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

While the Java client is executing, I see tons of requests enter `CLOSE_WAIT`, which means that these are being leaked.

**Comment by fxha** [comment]
@cowtowncoder Thanks for the quick fix. I can confirm that the read-case via `File` is working correctly.

@josh-byster 
I did a quick look at the initial issue and it seems to be an upstream issue in Java. Observed behavior with Java 17:

- [URL#openStream](https://github.com/openjdk/jdk/blob/f1143b1b57683665c81d24ff192a9babc30f28ea/src/java.base/share/classes/java/net/URL.java#L1162) creates a `URLConnection` depending on the URL that cannot be closed (no close method).
- In this case, a `sun.net.www.protocol.http.HttpURLConnection` instance is created.
- Afterwards `URLConnection` is used to create the input stream via `getInputStream`. `HttpURLConnection#getInputStream` is mostly a proxy for `getInputStream0`.
- `getInputStream0` creates the input stream and assignes it to itself.
- A `FileNotFoundException` exception is thrown due to HTTP 404 but the input stream isn't closed. See note *1.

Actually, there is a way to close the internal input stream by calling `disconnect` of [HttpURLConnection](https://github.com/openjdk/jdk/blob/f1143b1b57683665c81d24ff192a9babc30f28ea/src/java.base/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L3060). With a bit of magic, all sockets are successfully closed (see example below). Unfortunately, we cannot use this workaround because it's an internal Sun class.

*1: AFAIK, the input stream is internally never closed but maybe I'm missing something. The code is mostly 15 years old and not well structured 😄 . The exception in [HttpURLConnection](https://github.com/openjdk/jdk/blob/f1143b1b57683665c81d24ff192a9babc30f28ea/src/java.base/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L1989) seems to prevent the GC from freeing the `HttpURLConnection` instance that was created in `URL#openStream` (maybe due to the input stream that is never closed).

I just stepped though a few files but you could continue to locate the core issue if you like, or create an upstream issue. If you have this issue at work, my best bet is to report it to your "Java vendor" for prio support. Let me know, otherwise I'll eventually report the potential bug.

Tested with:

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment 21.9 (build 17.0.3+7)
OpenJDK 64-Bit Server VM 21.9 (build 17.0.3+7, mixed mode, sharing)
```

Example using nodejs server from above:

```java
URLConnection connection = new URL("http://localhost:3001/").openConnection();
try (InputStream stream = connection.getInputStream()) {
    System.out.println("Ok");
} catch (IOException ex) {
    ex.printStackTrace();
}

// # Manually, closing the connection:
// // Add compiler flag: --add-exports java.base/sun.net.www.protocol.http=ALL-UNNAMED
// connection.getClass().getMethod("disconnect").invoke(connection);

Thread.sleep(Integer.MAX_VALUE);
```

**Comment by cowtowncoder** [comment]
Hmmh. Are you sure? I was under impression that `CLOSE_WAIT` is TCP level state that is necessary after actual closing of connection, to avoid possible issues with reuse of ports if client or server reboots. I didn't think it would be a sign leakage.
I'll see if I can find a corroborating article.

**Comment by cowtowncoder** [comment]
Ok. Sounds like this is something that can probably not be solved on Jackson side when using JDK's http client.
If so, there seems to be 2 main paths forward:

1. Use of a better HTTP Client like OkHttp or Apache HC
2. Caller avoiding use of `URL`-based input source, creating it using alternate means (either better HTTP client as per above, or keeping track of `HttpURLConnection`

I don't think I would want to add a new dependency for this particular case in `jackson-databind`, but what could work would be an extension point for handler to open `InputStream` for an URL, and then providing an extension package that implements handler.

I'd be happy to hear more/better ideas, above is just my initial thinking on this. It is definitely not good to be leaking connections as that can easily cause issues during even short-living transient outages.

**Comment by fxha** [comment]
@cowtowncoder  I got a bit of time and looked closer into this. It's a non-issue, but maybe a bad design to have a connection which isn't closable and a separate stream. The connection itself isn't closed immediately but always freed by GC in all cases. You need to run a real application or busy wait with GC like this:

```java
while (true) {
  Thread.sleep(1_000);
  System.gc();
}
```

But I found another interesting way to guarantee that the connection is closed. Instead of using `URL#openStream` we could use the following approach:

```java
URLConnection connection = new URL(url).openConnection();
try (InputStream stream = connection.getInputStream()) {
  // parse JSON
} finally {
  // java.net.HttpURLConnection.HttpURLConnection
  if (connection instanceof HttpURLConnection) {
    ((HttpURLConnection) connection).disconnect();
  }
}
```

`java.net.HttpURLConnection.HttpURLConnection` is an abstract class which allows to close the connection immediately.

**Comment by cowtowncoder** [comment]
This might work for case of `ObjectMapper` / `ObjectReader`, as a special case. Unfortunately it would not be applicable to `JsonFactory.createParser(URL)` case.
But maybe it's worth doing nonetheless -- I will file a new issue for this case then (given this issue is closed for other work wrt `InputStream`)
