### ISSUE TITLE
Inconsistent behaviour with nulls for records

### ISSUE THREAD

**Issue by joca-bt** [FasterXML/jackson-databind#3847]
Forbidding nulls works correctly with classes but doesn't with records. Moreover, the behaviour with records changes if we use @JsonProperty.

Let's take the following ObjectMapper definition:
```
ObjectMapper objectMapper = JsonMapper.builder()
    .defaultSetterInfo(JsonSetter.Value.construct(Nulls.FAIL, Nulls.FAIL))
    .withCoercionConfigDefaults(config -> config.setCoercion(CoercionInputShape.String, CoercionAction.Fail))
    .build();
```

When testing nulls with a class everything works as expected:
```
public class Test {
    private String fieldName;

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
}

objectMapper.readValue("{ \"fieldName\": \"value\" }", Test.class); // ok (no exception is thrown)
objectMapper.readValue("{ \"fieldName\": null }", Test.class); // ok, throws InvalidNullException as expected
objectMapper.readValue("{ }", Test.class); // ok (no exception is thrown)
```

When testing the same class but adding @JsonProperty to it everything still works as expected:
```
public class Test {
    private @JsonProperty("field_name") String fieldName;

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
}

objectMapper.readValue("{ \"field_name\": \"value\" }", Test.class); // ok (no exception is thrown)
objectMapper.readValue("{ \"field_name\": null }", Test.class); // ok, throws InvalidNullException as expected
objectMapper.readValue("{ }", Test.class); // ok (no exception is thrown)
```

When testing nulls with a record null hating doesn't seem to be working:
```
public record Test(String fieldName) {}

objectMapper.readValue("{ \"fieldName\": \"value\" }", Test.class); // ok (no exception is thrown)
objectMapper.readValue("{ \"fieldName\": null }", Test.class); // not ok, was expecting a InvalidNullException to be thrown but it wasn't
objectMapper.readValue("{ }", Test.class); // ok (no exception is thrown)
```

When testing the same record but adding @JsonProperty to it null hating starts working but something else breaks:
```
public record Test(@JsonProperty("field_name") String fieldName) {}

objectMapper.readValue("{ \"field_name\": \"value\" }", Test.class); // ok (no exception is thrown)
objectMapper.readValue("{ \"field_name\": null }", Test.class); // ok, throws InvalidNullException as expected
objectMapper.readValue("{ }", Test.class); // not ok, throws InvalidNullException when it shouldn't
```

**Comment by joca-bt** [comment]
Here's a simple project replicating it.
[Uploading test2.zip…]()

**Comment by joca-bt** [comment]
You can inspect the zip without running it if you have security concerns.

Best,
João

**Comment by yihtserns** [comment]
@joca-bt From the attached project, I see that you're using version `2.14.2`.  I think this issue has been fixed in `2.15.0` by #3724, which is why #3848 wasn't able to reproduce the issue.

You can verify this by testing with [com.fasterxml.jackson.core:jackson-databind:2.15.0-rc2](https://central.sonatype.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.15.0-rc2) (don't forget to also upgrade any other Jackson dependency to the same version, to avoid [any unnecessary problems](https://github.com/FasterXML/jackson-databind/issues/3747#issuecomment-1492260082)).

**Comment by cowtowncoder** [comment]
@joca-bt if you are able to verify this against 2.15.0-rc2 please let  us know so I can close this (or keep open if issue remains).

**Comment by joca-bt** [comment]
I can test it next week. Where can I get the snapshot jar from?

**Comment by cowtowncoder** [comment]
@joca-bt Not snapshot, pre-release candidate (`2.15.0-rc2`), from Maven Central. :)

**Comment by joca-bt** [comment]
Ran the test cases in the zip I shared against 2.15.0-rc:
- Fixes line 27 `objectMapper.readValue("{ \"fieldName\": null }", Test3.class); // should throw but doesn't`. It now throws an `InvalidNullException`.
- Breaks line 28 `objectMapper.readValue("{ }", Test3.class);`. It now throws an `InvalidNullException` when it shouldn't.
- Line 32 remains the same (broken) `objectMapper.readValue("{ }", Test4.class); // throws but shouldn't`. Still throws an `InvalidNullException` when it shouldn't.

Overall, there are still some issues with records.

**Comment by yihtserns** [comment]
Right I totally missed the `{ }` scenario.

Actually your `class` is not identical to your `record`, e.g.:
```
public record Test(String fieldName) { }
```

...is actually equivalent to:
```
public class Test {
  private String fieldName;
  public Test(String fieldName) { this.fieldName = fieldName) }
}
```

...which when fed with empty hash `{ }`, will also throw `InvalidNullException`.

**Comment by cowtowncoder** [comment]
@yihtserns Missing value (absent) is generally differently handled from explicit `null` -- former causes no action wrt setters for example. But in case of Creators (constructors/factory methods) it needs to be handled so there can be a difference. For deserialization purposes `JsonDeserializer` does have separate methods (getNullValue(), getAbsentValue() to allow different coercions. This gets mostly tricky with things like `Optional<...>`.

**Comment by cowtowncoder** [comment]
I think this issue probably needs to be broken up into separate ones, targeting what is not apparently working with 2.15.0-rc2.
I am not sure all cases are working incorrectly, but they are easier to handle via separate issues usually as there may be separate root cases.

**Comment by yihtserns** [comment]
Created #3870 for fail explicit null + constructor creator + absent value = `InvalidNullException`.

**Comment by yihtserns** [comment]
Just to repeat myself, a Class equivalent of Record is not one with setter, but this:
```
public class Test {
    private final String fieldName;

    @ConstructorProperties({"fieldName"})
    public Test(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getFieldName() {
        return this.fieldName;
    }
}
```

...which will have this behaviour:
```
objectMapper.readValue("{ \"fieldName\": \"value\" }", Test.class); // no exception thrown
objectMapper.readValue("{ \"fieldName\": null }", Test.class); // throws InvalidNullException
objectMapper.readValue("{ }", Test.class); // throws InvalidNullException
```

There were some behavioural discrepancies between a Class with constructor creator vs Records, but they are now mostly aligned in `2.15.0`.

Knowing that, this issue is really about the behavioural difference between a POJO with constructor creator vs setter, i.e. #3870.

**Comment by cowtowncoder** [comment]
Not sure what might remain; with 2.18 rewrite of Property Introspection etc. Closing, may re-file for pieces that are not working (if any).

**Comment by joca-bt** [comment]
We tried updating to 2.18 and had an outage, so I guess there were some breaking changes (which can be actual fixes - we didn't have time to look and write tests).
