### ISSUE TITLE
Records with additional constructors failed to deserialize

### ISSUE THREAD

**Issue by GeorgiPetkov** [FasterXML/jackson-databind#3968]
**Describe the bug**
Records are not deserialized as before due to error:

> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Conflicting property-based creators: already had implicitly discovered creator [constructor for `RecordsDeserializationTest$TestRecord` (1 arg), annotations: [null], encountered another: [constructor for `RecordsDeserializationTest$TestRecord` (2 args), annotations: [null]
>  at [Source: (String)"{"a":"a", "b":"b"}"; line: 1, column: 1]

See the test below for the exact setup.

**Version information**
Which Jackson version(s) was this for?
2.15.0

**To Reproduce**

```
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.cfg.ConstructorDetector;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class RecordsDeserializationTest {

    private final ObjectMapper objectMapper = JsonMapper.builder()
            // commenting only this fixes the problem
            .addModules(new ParameterNamesModule())
            // commenting only this fixes the problem
            .constructorDetector(ConstructorDetector.USE_PROPERTIES_BASED)
            .build();

    record TestRecord(String a, String b) {

        // uncommenting only this fixes the problem
        // @JsonIgnore
        TestRecord(String c) {
            this(c, c);
        }
    }

    @Test
    void testDeserialization() throws JsonProcessingException {
        assertEquals(
                new TestRecord("a", "b"),
                objectMapper.readValue("{\"a\":\"a\", \"b\":\"b\"}", TestRecord.class));
    }
}
```

**Expected behavior**
The exact combination of configuration is not working in version 2.15.0.
There are 4 ways to fix it:
- remove module `ParameterNamesModule`
- don't use `USE_PROPERTIES_BASED` constructor detection
- add `@JsonIgnore` annotation to the extra constructor
- use version 2.13.4 on which this works

**Additional context**
The caveat here is that I can't use explicit `@JsonCreator` annotation on the primary constructor on a `record` (or I have to implement it just to add the annotation). Ideally, you should restore the old behavior. The `@JsonIgnore` approach seems like a hack to me.

**Comment by pjfanning** [comment]
What happens if you use v2.15.2? v2.15.0 introduced some big changes for `Record`s and some issues occurred. Some of those have been fixed since.

**Comment by yihtserns** [comment]
Still the same in v2.15.2.  I'll propose a PR to fix this since it is caused by #3724.

**Comment by cowtowncoder** [comment]
Ok, added some questions -- I think I understand the challenge, just seems tricky to combine defaulting of creator Mode (where Records definitely should default to Properties). But I understand that the issue then is just the conflict between 2 alternative Creators of same type.

However... for non-annotated ("implicit") case the Canonical constructor should win, I think; and in case of annotated (explicit) that one.

So I just want to try to make sure logic does not get even more fragile with various extra checks.

I hope to review this within 24 hours or so, but wanted add a quick note first.

**Comment by cowtowncoder** [comment]
Yes, I think this case should work. Ideally it would just work without changes, using the Canonical constructor and not being bothered about secondary one.

@yihtserns Why is the secondary constructor even considered here? I guess the problem is two-fold:

1. We do not want to mark Canonical constructor as explicit (annotated) to make it possible to replace with something that is, but
2. We do want to auto-detect public constructors in general.

In this case perhaps unification of POJO handling (POJOs do not have canonical constructors) and Records caused more problems than worth... again. :-/

Anyway: I hope to review the PR and see if that works. I wish it didn't have to change defaulting but would rather handle preference/priority of 3 levels we have (highest: annotated/explicit; medium: canonical; lowest: visible/public non-canonical).

**Comment by yihtserns** [comment]
> Why is the secondary constructor even considered here?

Because they may be considered for implicit delegating creator:
https://github.com/FasterXML/jackson-databind/blob/2cea7c9ce9cbdcb14e22838ea07937c376b7ab78/src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitCreatorsTest.java#L53-L75
https://github.com/FasterXML/jackson-databind/blob/2cea7c9ce9cbdcb14e22838ea07937c376b7ab78/src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitCreatorsTest.java#L277-L298

> In this case perhaps unification of POJO handling (POJOs do not have canonical constructors) and Records caused more problems than worth... again. :-/

Yeah sorry about that.  I'm regretting it a lot.

**Comment by cowtowncoder** [comment]
@yihtserns Don't regret too much; it wasn't possible to really know all the issues... partly due to limited test coverage.

**Comment by cowtowncoder** [comment]
Fixed via #3969 to be included eventually in 2.15.3
