### ISSUE TITLE
Dependency cannot be resolved using Gradle

### ISSUE THREAD

**Issue by fulcrum70** [FasterXML/jackson-databind#5031]
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Using Gradle 8.13 dependency configured like this

api group: 'tools.jackson.core', name: 'jackson-databind', version: '3.0.0-rc1'

Results in error:
Could not find com.fasterxml.jackson:jackson-bom:3.0-rc1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/3.0-rc1/jackson-bom-3.0-rc1.pom
     Required by:
         root project : > tools.jackson.core:jackson-databind:3.0.0-rc1 > com.fasterxml.jackson.core:jackson-annotations:3.0-rc1

### Version Information

3.0.0-rc1

**Comment by pjfanning** [comment]
This issue is already fixed and will be in the next RC release. Seems just to affect Gradle and not Maven or sbt. You can use the latest snapshot builds instead.

Snapshots are at https://s01.oss.sonatype.org/content/repositories/snapshots/tools/jackson/

**Comment by fulcrum70** [comment]
Using this declaration
api group: 'tools.jackson.core', name: 'jackson-databind', version: '3.0.0-rc2-SNAPSHOT'

similar error is still returned:

 Could not find com.fasterxml.jackson.core:jackson-annotations:3.0-rc2-SNAPSHOT.
     Searched in the following locations:
       - https://s01.oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/3.0-rc2-SNAPSHOT/maven-metadata.xml
       - https://s01.oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/3.0-rc2-SNAPSHOT/jackson-annotations-3.0-rc2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/3.0-rc2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/3.0-rc2-SNAPSHOT/jackson-annotations-3.0-rc2-SNAPSHOT.pom
     Required by:
         root project : > tools.jackson.core:jackson-databind:3.0.0-rc2-SNAPSHOT:20250318.003845-17
         root project : > tools.jackson.core:jackson-databind:3.0.0-rc2-SNAPSHOT:20250318.003845-17 > tools.jackson:jackson-bom:3.0.0-rc2-SNAPSHOT:20250318.034437-7

**Comment by cowtowncoder** [comment]
It might be some mix-up between snapshot repositories: while all other Jackson 3 components are under "new" Sonatype repos -- https://s01.oss.sonatype.org/content/repositories/snapshots/tools/jackson/ -- annotations are still under `com.fasterxml.jackson`, so https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/ .

So specifically, 3.0-rc2-SNAPSHOT of `jackson-annotations` is here:

    https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/3.0-rc2-SNAPSHOT/

Not sure how to help with that -- `jackson-annotations` pom.xml has both new and old Snapshot repos.

**Comment by cowtowncoder** [comment]
Ok while one part of the problem was resolved (bad version), there's alas second bigger problem -- wrong groupId. See: https://github.com/FasterXML/jackson-annotations/issues/286

So this will be resolved in `3.0.0-rc3`.
